### ISSUE TITLE
Decouple Interceptor from parser

### ISSUE THREAD

**Issue by trixpan** [srotya/cef#1]
@ambud love the simplicity of the code but I was wondering if you would mind decoupling the Interceptor and Parser into two different classes?

This way people developing for non-flume environments would still be able to use the parser you built.

Cheers

**Comment by ambud** [comment]
Sure, I will move the parsing method to another class however it's already a static method and the Flume dependency would still be there in Maven POM file.

If you are looking for a command line app/driver for the parser I can add that as a separate class.

**Comment by ambud** [comment]
Made changes and published to Maven central, version 0.0.15 has the changes.
