### ISSUE TITLE
Running parser with bogus data results in bogus parsing

### ISSUE THREAD

**Issue by trixpan** [srotya/cef#2]
@ambud 

I was extending your Utils class to fit our use case when I noticed that you basic parser returns success even when parsing something that it is clearly not CEF, e.g.

`parseToCEFOptimized(targetMap, " aaa ");`

I ended up not using your code but you may still want to fix it.

Cheers

**Comment by ambud** [comment]
Ack, thank you for the feedback; I will investigate the issue.

**Comment by ambud** [comment]
Because I wrote the parser to not throw exceptions on bogus invalid events, you were seeing this issue.

I have fixed the issue and written a test case as stated above to validate that an exception is thrown.

**Comment by ambud** [comment]
Fix version 0.0.17
